# Generated by Django 3.2.6 on 2021-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Nome')),
                ('Surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('rg', models.CharField(max_length=10, verbose_name='Rg')),
            ],
        ),
    ]
